"""add_device_firmware_update_event_log

Revision ID: 6abb0726e672
Revises: 6d75879b235f
Create Date: 2023-05-12 14:16:55.317923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abb0726e672'
down_revision = '6d75879b235f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_firmware_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_firmware_updates_device_id'), 'device_firmware_updates', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_firmware_updates_device_id'), table_name='device_firmware_updates')
    op.drop_table('device_firmware_updates')
    # ### end Alembic commands ###
