"""add_date_to_firmware_updates

Revision ID: 930a78a8d886
Revises: 6abb0726e672
Create Date: 2023-05-13 15:28:01.841176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930a78a8d886'
down_revision = '6abb0726e672'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_firmware_updates', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_firmware_updates', 'date')
    # ### end Alembic commands ###
