"""baseline

Revision ID: 6d75879b235f
Revises: 
Create Date: 2023-05-12 10:45:38.082218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d75879b235f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_project_id'), 'devices', ['project_id'], unique=False)
    op.create_table('project_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_memberships_project_id'), 'project_memberships', ['project_id'], unique=False)
    op.create_table('device_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_api_keys_device_id'), 'device_api_keys', ['device_id'], unique=False)
    op.create_table('project_membership_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_membership_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_membership_id'], ['project_memberships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_membership_api_keys_project_membership_id'), 'project_membership_api_keys', ['project_membership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_membership_api_keys_project_membership_id'), table_name='project_membership_api_keys')
    op.drop_table('project_membership_api_keys')
    op.drop_index(op.f('ix_device_api_keys_device_id'), table_name='device_api_keys')
    op.drop_table('device_api_keys')
    op.drop_index(op.f('ix_project_memberships_project_id'), table_name='project_memberships')
    op.drop_table('project_memberships')
    op.drop_index(op.f('ix_devices_project_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('projects')
    # ### end Alembic commands ###
